algo = input('digite algo ')
print('o tipo primitivo é:', type(algo))
print('é um numero?', algo.isnumeric())
print('tem espaços?', algo.isspace())
print('ele é alfabetico?', algo.isalpha())
print('ele é alfanumerico?', algo.isalnum())
print('ele é maiusculo?',algo.isupper())
print('ele é minusculo?', algo.islower())
print('ele é capitalizador', algo.istitle())